### ISSUE TITLE
Not able to import types and interfaces from other *.svelte files

### ISSUE THREAD

**Issue by blmhemu** [reepolee/svelte-routify-windi-vite#13] opened 2021-03-19 15:26 UTC
```
import type {filetype} from "../Modules.svelte";
```

The above code gives an error. Similar code when tested with svelte template, worked fine.

**Comment by alesvaupotic** [comment] 2021-03-20 21:48
I would need more info to reproduce this. Which Svelte template was working fine for you? Also on Vite?
Since this is typescript related, we are not putting much effort into it for now. If you solve it, feel free to send a PR.

**Comment by blmhemu** [comment] 2021-03-21 08:06
The official svelte and sapper templates worked fine... Yup it is typescript related. So there may be an issue there.

**Comment by alesvaupotic** [comment] 2021-03-21 08:23
Those templates work with Rollup. This is Vite based and would require some bending. I am not using TS, just merged a PR supporting it.

Leaving this issue open if anybody wants to chime in.

**Comment by alesvaupotic** [comment] 2021-04-03 14:36
Closing due to no activity in fortnight.

**Closed as completed by alesvaupotic** 2021-04-03 14:36 UTC
